kind: Deployment
apiVersion: apps/v1
metadata:
  name: influxdb
  namespace: demo1
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      volumes:
        - name: var-lib-influxdb
          persistentVolumeClaim:
            claimName: influxdb
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          name: influxdb
          ports:
            - containerPort: 8086
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: var-lib-influxdb
              mountPath: /var/lib/influxdb
          envFrom:
            - secretRef:
                name: influxdb-creds
          image: 'docker.io/influxdb:1.8'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600