apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: calculate-cthreads-value-task
  namespace: demo1
spec:
  params:
    - name: inputNumber
      type: string
      default: "1"
  results:
    - description: Generated CTHREADS number
      name: cthreadsNum
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      name: calculate-cthreads-value
      resources: {}
      script: >
        #!/usr/bin/env bash

        echo $(( $(inputs.params.inputNumber) + 15 )) | tr -d '\n' | tee $(results.cthreadsNum.path)
